# Generated by Django 4.1.7 on 2023-09-14 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemDataInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_time', models.DateTimeField(auto_now_add=True)),
                ('anti_virus_status', models.BooleanField(default=False)),
                ('firewall_virus_status', models.BooleanField(default=False)),
                ('cpu_percent', models.FloatField()),
                ('ram_percent', models.FloatField()),
                ('running_process', models.TextField()),
                ('usb_devices', models.TextField()),
                ('modified_files', models.TextField()),
                ('network_connection', models.TextField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.system')),
            ],
        ),
    ]
