# Generated by Django 4.1.7 on 2023-09-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_system_systemdatainstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdatainstance',
            name='installed_softwares',
            field=models.TextField(null=True),
        ),
    ]
