# Generated by Django 4.1.7 on 2023-09-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_delete_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='antivirus_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='system',
            name='firewall_notification',
            field=models.BooleanField(default=False),
        ),
    ]
